<?php

/**
 * @file
 * Contains dcnyc_pantheon.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dcnyc_pantheon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dcnyc_pantheon module.
    case 'help.page.dcnyc_pantheon':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a linked image for the Pantheon Footer') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dcnyc_pantheon_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['dcnyc_pantheon_footer'] = [
    'template' => 'dcnyc-patheon-block',
    'variables' => [
      'pantheon_url' => NULL,
      'pantheon_image' => NULL,
    ],
  ];
  return $theme;
}
