<?php

/**
 * @file
 * Contains dcnyc_social.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dcnyc_social_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dcnyc_social module.
    case 'help.page.dcnyc_social':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a configurable blocks for social links.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dcnyc_social_theme() {
  $theme = array();

  $theme['dcnyc_social_links'] = array(
    'template' => 'social-footer-block',
    'variables' => array(
      'twitter_page' => NULL,
      'facebook_page' => NULL,
      'gdo_page' => NULL,
    )
  );
  return $theme;
}
